language: cpp
env:
   - PYTHON_VERSION="3.4" IPYTHON_VERSION=3
   - PYTHON_VERSION="3.3" IPYTHON_VERSION=3
   - PYTHON_VERSION="2.7" IPYTHON_VERSION=3
   - PYTHON_VERSION="3.3" IPYTHON_VERSION=2
   - PYTHON_VERSION="2.7" IPYTHON_VERSION=2
before_install:
   # Move out of git directory to build root.
   - cd ../..
   - pwd
install:
   # Download and configure conda.
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --set show_channel_urls True
   - source activate root
   # Install basic conda dependencies.
   - touch $HOME/miniconda/conda-meta/pinned
   - echo "conda-build ==1.16.0" >> $HOME/miniconda/conda-meta/pinned
   - conda update --all
   - conda install conda-build
   # Build the conda package for runipy.
   - cd $TRAVIS_REPO_SLUG
   - VERSION=`python setup.py --version`
   - echo $VERSION
   # Create the test environment and install dependencies.
   - conda create --use-local -n testenv python=$PYTHON_VERSION
   - touch $HOME/miniconda/envs/testenv/conda-meta/pinned
   - echo "ipython ${IPYTHON_VERSION}.*" >> $HOME/miniconda/envs/testenv/conda-meta/pinned
   - echo "ipython-notebook ${IPYTHON_VERSION}.*" >> $HOME/miniconda/envs/testenv/conda-meta/pinned
   - python setup.py install
   - source activate testenv
   # Install other dependencies.
   - conda install numpy scipy matplotlib h5py
   # Clean up downloads as there are quite a few and they waste space/memory.
   - conda clean -tipsy
   - rm -rfv $HOME/.cache/pip
script:
   # Run tests.
   - python test.py --verbose
# Use container format for TravisCI.
sudo: false
